"""
XML Executor for Adding Materials to JobBOSS Jobs

Reads a manifest and XML files generated by job_material_generator.py
and executes the operation to add materials to jobs via the COM object.

This is the second step in the two-phase update process:
1. job_material_generator.py - Generate XML files for review
2. job_material_executor.py  - Execute the reviewed XML files (this script)

Usage:
    python job_material_executor.py --manifest ./pending_updates/manifest.json --user USERNAME --password PASSWORD
    
    # Or with environment variables:
    set JOBBOSS_USER=your_username
    set JOBBOSS_PASSWORD=your_password
    python job_material_executor.py --manifest ./pending_updates/manifest.json
"""

import os
import sys
import json
import re
import argparse
from datetime import datetime

try:
    import win32com.client
except ImportError:
    print("ERROR: pywin32 is not installed. Run: pip install pywin32")
    sys.exit(1)


# =============================================================================
# Response Parsing
# =============================================================================

def parse_response_for_last_updated(response_xml: str) -> str | None:
    """Extract LastUpdated value from JobQueryRs response."""
    match = re.search(r'<LastUpdated>([^<]+)</LastUpdated>', response_xml)
    if match:
        return match.group(1)
    return None


def parse_response_for_error(response_xml: str) -> str | None:
    """Check response for error messages."""
    # Success case
    if '<StatusCode>0</StatusCode>' in response_xml:
        return None
    
    # Try to extract error message
    match = re.search(r'<StatusMessage>([^<]+)</StatusMessage>', response_xml)
    if match:
        return match.group(1)
    
    match = re.search(r'<ErrorMessage>([^<]+)</ErrorMessage>', response_xml)
    if match:
        return match.group(1)
    
    # Check for non-zero status code
    match = re.search(r'<StatusCode>([^0][^<]*)</StatusCode>', response_xml)
    if match:
        return f"Status code: {match.group(1)}"
    
    return None


def check_response_success(response_xml: str) -> bool:
    """Check if response indicates success."""
    return '<StatusCode>0</StatusCode>' in response_xml


# =============================================================================
# Execution
# =============================================================================

def execute_job_material_add(manifest_path: str, username: str, password: str, 
                              dry_run: bool = False, verbose: bool = False,
                              log_dir: str | None = None) -> dict:
    """
    Execute adding material to a job from a manifest.
    
    Args:
        manifest_path: Path to manifest.json from job_material_generator.py
        username: JobBOSS username
        password: JobBOSS password
        dry_run: If True, show what would be done without executing
        verbose: If True, print full XML requests and responses
        log_dir: If provided, save all XML requests/responses to this directory
        
    Returns:
        Dict with 'success', 'failed', and 'errors' keys
    """
    results = {"success": False, "failed": False, "errors": []}
    
    # Set up logging directory if requested
    if log_dir:
        os.makedirs(log_dir, exist_ok=True)
        log_index = 0
        
        def save_xml_log(operation: str, direction: str, xml_content: str):
            nonlocal log_index
            log_index += 1
            filename = f"{log_index:03d}_{operation}_{direction}.xml"
            filepath = os.path.join(log_dir, filename)
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(xml_content)
            print(f"  Logged: {filename}")
    else:
        def save_xml_log(operation: str, direction: str, xml_content: str):
            pass  # No-op when logging is disabled
    
    # Load manifest
    manifest_dir = os.path.dirname(os.path.abspath(manifest_path))
    with open(manifest_path, 'r', encoding='utf-8') as f:
        manifest = json.load(f)
    
    print(f"Manifest generated at: {manifest['generated_at']}")
    print(f"Operation: {manifest['operation']}")
    print(f"Job ID: {manifest['job_id']}")
    print(f"Material ID: {manifest['material_id']}")
    print(f"Quantity: {manifest['quantity']}")
    print()
    
    # Dry run - just show what would happen
    if dry_run:
        print("DRY RUN MODE - No changes will be made")
        print()
        print(f"Would add {manifest['quantity']} units of material {manifest['material_id']} to job {manifest['job_id']}")
        print()
        print("To execute for real, remove the --dry-run flag.")
        return results
    
    # Create COM object
    print("Connecting to JobBOSS...")
    try:
        jb = win32com.client.Dispatch("JBInterface.JBRequestProcessor")
    except Exception as e:
        error_msg = f"Failed to create JobBOSS COM object: {e}"
        print(f"ERROR: {error_msg}")
        print("Make sure JobBOSS is installed and the SDK is registered.")
        results["errors"].append(error_msg)
        return results
    
    # Create session
    print(f"Creating session for user: {username}")
    try:
        result = jb.CreateSession(username, password, "")
        # COM returns tuple: (session_id, error_msg) due to byref parameter
        if isinstance(result, tuple):
            session_id, error_msg = result[0], result[1] if len(result) > 1 else ""
        else:
            session_id = result
            error_msg = ""
        
        if not session_id:
            error_msg = f"Failed to create session: {error_msg}"
            print(f"ERROR: {error_msg}")
            results["errors"].append(error_msg)
            return results
        print(f"Session created: {session_id}")
    except Exception as e:
        error_msg = f"Failed to create session: {e}"
        print(f"ERROR: {error_msg}")
        results["errors"].append(error_msg)
        return results
    
    try:
        job_id = manifest["job_id"]
        material_id = manifest["material_id"]
        quantity = manifest["quantity"]
        
        print(f"\nProcessing: Add material {material_id} to job {job_id}")
        
        # Step 1: Load and execute query XML to get LastUpdated
        query_path = os.path.join(manifest_dir, manifest["query_file"])
        
        if not os.path.exists(query_path):
            error = f"Query file not found: {query_path}"
            print(f"  ERROR: {error}")
            results["failed"] = True
            results["errors"].append(error)
            return results
        
        with open(query_path, 'r', encoding='utf-8') as f:
            query_xml = f.read()
        
        # Replace session placeholder
        query_xml = query_xml.replace("{{SESSION_ID}}", session_id)
        
        print(f"  Querying job for LastUpdated...")
        if verbose:
            print(f"  --- QUERY REQUEST ---")
            print(query_xml)
            print(f"  --- END REQUEST ---")
        
        save_xml_log("query_job", "request", query_xml)
        
        try:
            response = jb.ProcessRequest(query_xml)
            save_xml_log("query_job", "response", response)
            if verbose:
                print(f"  --- QUERY RESPONSE ---")
                print(response)
                print(f"  --- END RESPONSE ---")
        except Exception as e:
            error = f"Query failed: {e}"
            print(f"  ERROR: {error}")
            results["failed"] = True
            results["errors"].append(error)
            return results
        
        # Check for errors in query response
        error = parse_response_for_error(response)
        if error:
            print(f"  ERROR: {error}")
            results["failed"] = True
            results["errors"].append(error)
            return results
        
        # Extract LastUpdated
        last_updated = parse_response_for_last_updated(response)
        if not last_updated:
            error = "Job not found or no LastUpdated in response"
            print(f"  ERROR: {error}")
            results["failed"] = True
            results["errors"].append(error)
            return results
        
        print(f"  LastUpdated: {last_updated}")
        
        # Step 2: Load and execute add material XML
        add_path = os.path.join(manifest_dir, manifest["add_file"])
        
        if not os.path.exists(add_path):
            error = f"Add material file not found: {add_path}"
            print(f"  ERROR: {error}")
            results["failed"] = True
            results["errors"].append(error)
            return results
        
        with open(add_path, 'r', encoding='utf-8') as f:
            add_xml = f.read()
        
        # Replace placeholders with actual values
        add_xml = add_xml.replace("{{SESSION_ID}}", session_id)
        add_xml = add_xml.replace("{{LAST_UPDATED}}", last_updated)
        
        print(f"  Executing add material operation...")
        if verbose:
            print(f"  --- ADD MATERIAL REQUEST ---")
            print(add_xml)
            print(f"  --- END REQUEST ---")
        
        save_xml_log("add_material", "request", add_xml)
        
        try:
            response = jb.ProcessRequest(add_xml)
            save_xml_log("add_material", "response", response)
            if verbose:
                print(f"  --- ADD MATERIAL RESPONSE ---")
                print(response)
                print(f"  --- END RESPONSE ---")
        except Exception as e:
            error = f"Add material failed: {e}"
            print(f"  ERROR: {error}")
            results["failed"] = True
            results["errors"].append(error)
            return results
        
        # Check for errors in add material response
        error = parse_response_for_error(response)
        if error:
            print(f"  ERROR: {error}")
            results["failed"] = True
            results["errors"].append(error)
            return results
        
        if check_response_success(response):
            print(f"  SUCCESS: Added {quantity} units of {material_id} to job {job_id}")
            results["success"] = True
        else:
            error = "Unknown error - response did not indicate success"
            print(f"  WARNING: {error}")
            results["failed"] = True
            results["errors"].append(error)
    
    finally:
        # Always close the session
        print("\nClosing session...")
        try:
            jb.CloseSession(session_id)
            print("Session closed.")
        except Exception as e:
            print(f"Warning: Failed to close session: {e}")
    
    return results


# =============================================================================
# CLI
# =============================================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description='Execute adding materials to JobBOSS jobs from generated XML files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
    # Execute with credentials
    python job_material_executor.py --manifest ./pending_updates/manifest.json --user myuser --password mypass
    
    # Dry run (preview only)
    python job_material_executor.py --manifest ./pending_updates/manifest.json --user myuser --password mypass --dry-run
    
    # Verbose mode (show XML requests/responses)
    python job_material_executor.py --manifest ./pending_updates/manifest.json --user myuser --password mypass --verbose
    
    # Log all XML to files for support
    python job_material_executor.py --manifest ./pending_updates/manifest.json --user myuser --password mypass --log-xml ./xml_logs
    
    # Using environment variables
    set JOBBOSS_USER=myuser
    set JOBBOSS_PASSWORD=mypass
    python job_material_executor.py --manifest ./pending_updates/manifest.json
        '''
    )
    
    parser.add_argument(
        '--manifest', '-m',
        required=True,
        help='Path to manifest.json from job_material_generator.py'
    )
    parser.add_argument(
        '--user', '-u',
        default=os.environ.get('JOBBOSS_USER'),
        help='JobBOSS username (or set JOBBOSS_USER env var)'
    )
    parser.add_argument(
        '--password', '-p',
        default=os.environ.get('JOBBOSS_PASSWORD'),
        help='JobBOSS password (or set JOBBOSS_PASSWORD env var)'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be done without executing'
    )
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Show full XML requests and responses'
    )
    parser.add_argument(
        '--log-xml',
        nargs='?',
        const='./xml_logs',
        default=None,
        metavar='DIR',
        help='Save all XML requests and responses to directory (default: ./xml_logs)'
    )
    
    return parser.parse_args()


def main():
    args = parse_args()
    
    print("=" * 60)
    print("JobBOSS Job Material Executor")
    print("=" * 60)
    print(f"Timestamp: {datetime.now().isoformat()}")
    print()
    
    # Validate credentials
    if not args.user:
        print("ERROR: JobBOSS username required.")
        print("       Use --user or set JOBBOSS_USER environment variable.")
        sys.exit(1)
    
    if not args.password:
        print("ERROR: JobBOSS password required.")
        print("       Use --password or set JOBBOSS_PASSWORD environment variable.")
        sys.exit(1)
    
    # Validate manifest
    if not os.path.exists(args.manifest):
        print(f"ERROR: Manifest not found: {args.manifest}")
        sys.exit(1)
    
    print(f"Manifest: {args.manifest}")
    print()
    
    # Execute operation
    results = execute_job_material_add(args.manifest, args.user, args.password, args.dry_run, args.verbose, args.log_xml)
    
    # Print summary
    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    if results["success"]:
        print("Status: SUCCESS")
    elif results["failed"]:
        print("Status: FAILED")
        if results["errors"]:
            print("\nErrors:")
            for error in results["errors"]:
                print(f"  - {error}")
    else:
        print("Status: DRY RUN (no changes made)")
    
    # Exit code
    if results["failed"] or results["errors"]:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
