"""
XML Executor for JobBOSS Material Quantity Updates

Reads a manifest and XML files generated by xml_generator.py
and executes the updates against JobBOSS via the COM object.

This is the second step in the two-phase update process:
1. xml_generator.py - Generate XML files for review
2. xml_executor.py  - Execute the reviewed XML files (this script)

Usage:
    python xml_executor.py --manifest ./pending_updates/manifest.json --user USERNAME --password PASSWORD
    
    # Or with environment variables:
    set JOBBOSS_USER=your_username
    set JOBBOSS_PASSWORD=your_password
    python xml_executor.py --manifest ./pending_updates/manifest.json
"""

import os
import sys
import json
import re
import argparse
from datetime import datetime

try:
    import win32com.client
except ImportError:
    print("ERROR: pywin32 is not installed. Run: pip install pywin32")
    sys.exit(1)


# =============================================================================
# Response Parsing
# =============================================================================

def parse_response_for_last_updated(response_xml: str) -> str | None:
    """Extract LastUpdated value from MaterialQueryRs response."""
    match = re.search(r'<LastUpdated>([^<]+)</LastUpdated>', response_xml)
    if match:
        return match.group(1)
    return None


def parse_response_for_error(response_xml: str) -> str | None:
    """Check response for error messages."""
    # Success case
    if '<StatusCode>0</StatusCode>' in response_xml:
        return None
    
    # Try to extract error message
    match = re.search(r'<StatusMessage>([^<]+)</StatusMessage>', response_xml)
    if match:
        return match.group(1)
    
    match = re.search(r'<ErrorMessage>([^<]+)</ErrorMessage>', response_xml)
    if match:
        return match.group(1)
    
    # Check for non-zero status code
    match = re.search(r'<StatusCode>([^0][^<]*)</StatusCode>', response_xml)
    if match:
        return f"Status code: {match.group(1)}"
    
    return None


def check_response_success(response_xml: str) -> bool:
    """Check if response indicates success."""
    return '<StatusCode>0</StatusCode>' in response_xml


# =============================================================================
# Execution
# =============================================================================

def execute_updates(manifest_path: str, username: str, password: str, 
                    dry_run: bool = False) -> dict:
    """
    Execute the material updates from a manifest.
    
    Args:
        manifest_path: Path to manifest.json from xml_generator.py
        username: JobBOSS username
        password: JobBOSS password
        dry_run: If True, show what would be done without executing
        
    Returns:
        Dict with 'success', 'failed', and 'errors' lists
    """
    results = {"success": [], "failed": [], "errors": []}
    
    # Load manifest
    manifest_dir = os.path.dirname(os.path.abspath(manifest_path))
    with open(manifest_path, 'r', encoding='utf-8') as f:
        manifest = json.load(f)
    
    print(f"Manifest generated at: {manifest['generated_at']}")
    print(f"Reason code: {manifest['reason_id']}")
    print(f"Materials to update: {manifest['total_materials']}")
    print(f"Total pieces to remove: {manifest['total_pieces']}")
    print()
    
    # Dry run - just show what would happen
    if dry_run:
        print("DRY RUN MODE - No changes will be made")
        print()
        print("Would execute the following updates:")
        for item in manifest["materials"]:
            print(f"  {item['material_id']}: {item['quantity_change']:+d} ({item['occurrences']} pieces)")
        print()
        print("To execute for real, remove the --dry-run flag.")
        return results
    
    # Create COM object
    print("Connecting to JobBOSS...")
    try:
        jb = win32com.client.Dispatch("JBInterface.JBRequestProcessor")
    except Exception as e:
        error_msg = f"Failed to create JobBOSS COM object: {e}"
        print(f"ERROR: {error_msg}")
        print("Make sure JobBOSS is installed and the SDK is registered.")
        results["errors"].append(error_msg)
        return results
    
    # Create session
    print(f"Creating session for user: {username}")
    try:
        result = jb.CreateSession(username, password, "")
        # COM returns tuple: (session_id, error_msg) due to byref parameter
        if isinstance(result, tuple):
            session_id, error_msg = result[0], result[1] if len(result) > 1 else ""
        else:
            session_id = result
            error_msg = ""
        
        if not session_id:
            error_msg = f"Failed to create session: {error_msg}"
            print(f"ERROR: {error_msg}")
            results["errors"].append(error_msg)
            return results
        print(f"Session created: {session_id}")
    except Exception as e:
        error_msg = f"Failed to create session: {e}"
        print(f"ERROR: {error_msg}")
        results["errors"].append(error_msg)
        return results
    
    try:
        # Process each material
        for item in manifest["materials"]:
            material_id = item["material_id"]
            quantity_change = item["quantity_change"]
            
            print(f"\nProcessing: {material_id} ({quantity_change:+d})")
            
            # Step 1: Load and execute query XML to get LastUpdated
            query_path = os.path.join(manifest_dir, item["query_file"])
            
            if not os.path.exists(query_path):
                error = f"Query file not found: {query_path}"
                print(f"  ERROR: {error}")
                results["failed"].append({
                    "material_id": material_id,
                    "quantity_change": quantity_change,
                    "error": error
                })
                continue
            
            with open(query_path, 'r', encoding='utf-8') as f:
                query_xml = f.read()
            
            # Replace session placeholder
            query_xml = query_xml.replace("{{SESSION_ID}}", session_id)
            
            print(f"  Querying for LastUpdated...")
            try:
                response = jb.ProcessRequest(query_xml)
            except Exception as e:
                error = f"Query failed: {e}"
                print(f"  ERROR: {error}")
                results["failed"].append({
                    "material_id": material_id,
                    "quantity_change": quantity_change,
                    "error": error
                })
                continue
            
            # Check for errors in query response
            error = parse_response_for_error(response)
            if error:
                print(f"  ERROR: {error}")
                results["failed"].append({
                    "material_id": material_id,
                    "quantity_change": quantity_change,
                    "error": error
                })
                continue
            
            # Extract LastUpdated
            last_updated = parse_response_for_last_updated(response)
            if not last_updated:
                error = "Material not found or no LastUpdated in response"
                print(f"  ERROR: {error}")
                results["failed"].append({
                    "material_id": material_id,
                    "quantity_change": quantity_change,
                    "error": error
                })
                continue
            
            print(f"  LastUpdated: {last_updated}")
            
            # Step 2: Load and execute update XML
            update_path = os.path.join(manifest_dir, item["update_file"])
            
            if not os.path.exists(update_path):
                error = f"Update file not found: {update_path}"
                print(f"  ERROR: {error}")
                results["failed"].append({
                    "material_id": material_id,
                    "quantity_change": quantity_change,
                    "error": error
                })
                continue
            
            with open(update_path, 'r', encoding='utf-8') as f:
                update_xml = f.read()
            
            # Replace placeholders with actual values
            update_xml = update_xml.replace("{{SESSION_ID}}", session_id)
            update_xml = update_xml.replace("{{LAST_UPDATED}}", last_updated)
            
            print(f"  Executing update...")
            try:
                response = jb.ProcessRequest(update_xml)
            except Exception as e:
                error = f"Update failed: {e}"
                print(f"  ERROR: {error}")
                results["failed"].append({
                    "material_id": material_id,
                    "quantity_change": quantity_change,
                    "error": error
                })
                continue
            
            # Check for errors in update response
            error = parse_response_for_error(response)
            if error:
                print(f"  ERROR: {error}")
                results["failed"].append({
                    "material_id": material_id,
                    "quantity_change": quantity_change,
                    "error": error
                })
                continue
            
            if check_response_success(response):
                print(f"  SUCCESS: Adjusted by {quantity_change:+d}")
                results["success"].append({
                    "material_id": material_id,
                    "quantity_change": quantity_change
                })
            else:
                error = "Unknown error - response did not indicate success"
                print(f"  WARNING: {error}")
                results["failed"].append({
                    "material_id": material_id,
                    "quantity_change": quantity_change,
                    "error": error
                })
    
    finally:
        # Always close the session
        print("\nClosing session...")
        try:
            jb.CloseSession(session_id)
            print("Session closed.")
        except Exception as e:
            print(f"Warning: Failed to close session: {e}")
    
    return results


# =============================================================================
# CLI
# =============================================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description='Execute JobBOSS material updates from generated XML files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
    # Execute with credentials
    python xml_executor.py --manifest ./pending_updates/manifest.json --user myuser --password mypass
    
    # Dry run (preview only)
    python xml_executor.py --manifest ./pending_updates/manifest.json --user myuser --password mypass --dry-run
    
    # Using environment variables
    set JOBBOSS_USER=myuser
    set JOBBOSS_PASSWORD=mypass
    python xml_executor.py --manifest ./pending_updates/manifest.json
        '''
    )
    
    parser.add_argument(
        '--manifest', '-m',
        required=True,
        help='Path to manifest.json from xml_generator.py'
    )
    parser.add_argument(
        '--user', '-u',
        default=os.environ.get('JOBBOSS_USER'),
        help='JobBOSS username (or set JOBBOSS_USER env var)'
    )
    parser.add_argument(
        '--password', '-p',
        default=os.environ.get('JOBBOSS_PASSWORD'),
        help='JobBOSS password (or set JOBBOSS_PASSWORD env var)'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be done without executing'
    )
    
    return parser.parse_args()


def main():
    args = parse_args()
    
    print("=" * 60)
    print("JobBOSS XML Executor")
    print("=" * 60)
    print(f"Timestamp: {datetime.now().isoformat()}")
    print()
    
    # Validate credentials
    if not args.user:
        print("ERROR: JobBOSS username required.")
        print("       Use --user or set JOBBOSS_USER environment variable.")
        sys.exit(1)
    
    if not args.password:
        print("ERROR: JobBOSS password required.")
        print("       Use --password or set JOBBOSS_PASSWORD environment variable.")
        sys.exit(1)
    
    # Validate manifest
    if not os.path.exists(args.manifest):
        print(f"ERROR: Manifest not found: {args.manifest}")
        sys.exit(1)
    
    print(f"Manifest: {args.manifest}")
    print()
    
    # Execute updates
    results = execute_updates(args.manifest, args.user, args.password, args.dry_run)
    
    # Print summary
    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"Successful: {len(results['success'])}")
    print(f"Failed:     {len(results['failed'])}")
    
    if results["success"]:
        total_adjusted = sum(item["quantity_change"] for item in results["success"])
        print(f"Total quantity adjusted: {total_adjusted:+d}")
    
    if results["failed"]:
        print("\nFailed materials:")
        for item in results["failed"]:
            print(f"  - {item['material_id']}: {item['error']}")
    
    if results["errors"]:
        print("\nGeneral errors:")
        for error in results["errors"]:
            print(f"  - {error}")
    
    # Exit code
    if results["failed"] or results["errors"]:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
